<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Tests for EurovisionHue.</Description>
    <OutputType>Exe</OutputType>
    <RootNamespace>MartinCostello.EurovisionHue</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>MartinCostello.EurovisionHue</UserSecretsId>
    <UseDefaultCodeAnalysisRuleSet>true</UseDefaultCodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EurovisionHue\EurovisionHue.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="JustEat.HttpClientInterception" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Include="SolutionRoot" Value="$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)\..\..'))" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
    <Threshold>85,75,90</Threshold>
  </PropertyGroup>
</Project>
