name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
    tags: [ v* ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions: {}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  FORCE_COLOR: 3
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  build:
    name: ${{ matrix.os-name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-name: macos
            # renovate: datasource=github-runners depType=github-runner
            runner: macos-26
          - os-name: linux
            # renovate: datasource=github-runners depType=github-runner
            runner: ubuntu-24.04
          - os-name: windows
            # renovate: datasource=github-runners depType=github-runner
            runner: windows-2025

    steps:

    - name: Update agent configuration
      shell: pwsh
      run: |
        if ($IsWindows) {
          "DOTNET_INSTALL_DIR=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "DOTNET_ROOT=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "NUGET_PACKAGES=D:\.nuget\packages" >> ${env:GITHUB_ENV}
        } else {
          $nugetHome = "~/.nuget/packages"
          if (-Not (Test-Path $nugetHome)) {
            New-Item -Path $nugetHome -Type Directory -Force | Out-Null
          }
          $nugetHome = Resolve-Path $nugetHome
          "NUGET_PACKAGES=$nugetHome" >> ${env:GITHUB_ENV}
        }

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Get Git commit timestamp
      id: get-commit-timestamp
      shell: pwsh
      run: |
        "epoch=$(git log -1 --pretty=%ct)" >> ${env:GITHUB_OUTPUT}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0

    - name: Build, Test and Publish
      shell: pwsh
      run: ./build.ps1
      env:
        SOURCE_DATE_EPOCH: ${{ steps.get-commit-timestamp.outputs.epoch }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        flags: ${{ matrix.os-name }}

    - name: Upload test results to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      if: ${{ !cancelled() }}
      with:
        flags: ${{ matrix.os-name }}
        report_type: test_results

    - name: Build container image
      if: runner.os == 'Linux'
      shell: pwsh
      run: docker build --build-arg SOURCE_DATE_EPOCH=${env:SOURCE_DATE_EPOCH} .
      env:
        SOURCE_DATE_EPOCH: ${{ steps.get-commit-timestamp.outputs.epoch }}

  publish:
    needs: build
    runs-on: ubuntu-24.04
    if: |
      github.event.repository.fork == false &&
      (github.ref_name == github.event.repository.default_branch ||
       startsWith(github.ref, 'refs/tags/v'))

    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io

    environment:
      name: publish
      url: ${{ format('{0}/{1}/pkgs/container/{2}', github.server_url, github.repository, 'eurovision-hue') }}

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Get information for container build
        id: get-info-for-container
        shell: pwsh
        run: |
          $gitCommitEpoch = git log -1 --pretty=%ct
          Write-Output "git-commit-epoch=${gitCommitEpoch}" >> ${env:GITHUB_OUTPUT}

          $dockerfileLines = Get-Content -Raw -Path "Dockerfile" | Select-String -Pattern 'FROM\s+(.+)' -AllMatches
          $lastFrom = ($dockerfileLines.Matches | ForEach-Object { $_.Groups[1].Value })[-1]
          if ($lastFrom -match '^(.*?)@(sha256:[a-fA-F0-9]+)(\s.*)?$') {
            $imageName = $Matches[1]
            $digest = $Matches[2]
            Write-Output "base-image-digest=${digest}" >> ${env:GITHUB_OUTPUT}
            Write-Output "base-image-name=${imageName}" >> ${env:GITHUB_OUTPUT}
          }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log in to GitHub Container registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container images
        id: metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_NAME) }}
          labels: |
            org.opencontainers.image.authors=${{ format('{0}/{1}', github.server_url, github.repository_owner) }}
            org.opencontainers.image.base.digest=${{ steps.get-info-for-container.outputs.base-image-digest }}
            org.opencontainers.image.base.name=${{ steps.get-info-for-container.outputs.base-image-name }}
            org.opencontainers.image.documentation=${{ format('{0}/{1}/blob/{2}/README.md', github.server_url, github.repository, github.sha) }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}
            org.opencontainers.image.source=${{ format('{0}/{1}', github.server_url, github.repository) }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            type=edge,branch=main
            type=match,pattern=v(.*),group=1

      - name: Build and push container images
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        env:
          SOURCE_DATE_EPOCH: ${{ steps.get-info-for-container.outputs.git-commit-epoch }}
        with:
          annotations: ${{ steps.metadata.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          sbom: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          push-to-registry: true
          subject-name: ${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_NAME) }}
          subject-digest: ${{ steps.push.outputs.digest }}

      - name: Verify attestations
        shell: bash
        env:
          CONTAINER_IMAGE_DIGEST: ${{ format('oci://{0}/{1}@{2}', env.REGISTRY, env.IMAGE_NAME, steps.push.outputs.digest) }}
          CONTAINER_IMAGE_LABEL: ${{ format('oci://{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, github.ref_name == github.event.repository.default_branch && 'edge' || 'latest') }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for image in "${CONTAINER_IMAGE_DIGEST}" "${CONTAINER_IMAGE_LABEL}"; do
             attempts=0
             until gh attestation verify --repo "${GITHUB_REPOSITORY}" "${image}"; do
               attempts=$((attempts + 1))
               if [ "${attempts}" -ge 6 ]; then
                 echo "Attestation verification failed for ${image} after ${attempts} attempts."
                 exit 1
               fi
               sleep 5s
             done
           done

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        env:
          # renovate: datasource=github-releases depName=cosign packageName=sigstore/cosign
          COSIGN_VERSION: v3.1.1
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Sign container images
        shell: bash
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
          TAGS: ${{ steps.metadata.outputs.tags }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes "{}@${DIGEST}" --annotations "ref=${GITHUB_SHA}" --annotations "repo=${GITHUB_REPOSITORY}" --annotations "workflow=${GITHUB_WORKFLOW}"

      - name: Verify container image signatures
        shell: bash
        env:
          CERTIFICATE_IDENTITY: ${{ format('{0}/{1}', github.server_url, github.workflow_ref) }}
          CERTIFICATE_OIDC_ISSUER: "https://token.actions.githubusercontent.com"
          CONTAINER_IMAGE_DIGEST: ${{ format('{0}/{1}@{2}', env.REGISTRY, env.IMAGE_NAME, steps.push.outputs.digest) }}
          CONTAINER_IMAGE_LABEL: ${{ format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, github.ref_name == github.event.repository.default_branch && 'edge' || 'latest') }}
        run: |
          cosign verify "${CONTAINER_IMAGE_DIGEST}" --certificate-identity "${CERTIFICATE_IDENTITY}" --certificate-oidc-issuer "${CERTIFICATE_OIDC_ISSUER}" || exit 1
          cosign verify "${CONTAINER_IMAGE_LABEL}" --certificate-identity "${CERTIFICATE_IDENTITY}" --certificate-oidc-issuer "${CERTIFICATE_OIDC_ISSUER}" || exit 1
