name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
    tags: [ v* ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions: {}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  FORCE_COLOR: 3
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  build:
    name: ${{ matrix.os-name }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-name: macos
            # renovate: datasource=github-runners depType=github-runner
            runner: macos-26
          - os-name: linux
            # renovate: datasource=github-runners depType=github-runner
            runner: ubuntu-24.04
          - os-name: windows
            # renovate: datasource=github-runners depType=github-runner
            runner: windows-2025

    steps:

    - name: Update agent configuration
      shell: pwsh
      run: |
        if ($IsWindows) {
          "DOTNET_INSTALL_DIR=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "DOTNET_ROOT=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "NUGET_PACKAGES=D:\.nuget\packages" >> ${env:GITHUB_ENV}
        } else {
          $nugetHome = "~/.nuget/packages"
          if (-Not (Test-Path $nugetHome)) {
            New-Item -Path $nugetHome -Type Directory -Force | Out-Null
          }
          $nugetHome = Resolve-Path $nugetHome
          "NUGET_PACKAGES=$nugetHome" >> ${env:GITHUB_ENV}
        }

    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: Build, Test and Publish
      shell: pwsh
      run: ./build.ps1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        flags: ${{ matrix.os-name }}

    - name: Upload test results to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      if: ${{ !cancelled() }}
      with:
        flags: ${{ matrix.os-name }}
        report_type: test_results

    - name: Build container image
      if: runner.os == 'Linux'
      shell: pwsh
      run: docker build .

  publish:
    needs: build
    runs-on: ubuntu-24.04
    if: |
      github.event.repository.fork == false &&
      (github.ref_name == github.event.repository.default_branch ||
       startsWith(github.ref, 'refs/tags/v'))

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Get information for container build
        id: get-info-for-container
        shell: pwsh
        run: |
          $gitCommitEpoch = git log -1 --pretty=%ct
          Write-Output "git-commit-epoch=${gitCommitEpoch}" >> ${env:GITHUB_OUTPUT}

          $dockerfileLines = Get-Content -Raw -Path "Dockerfile" | Select-String -Pattern 'FROM\s+(.+)' -AllMatches
          $lastFrom = ($dockerfileLines.Matches | ForEach-Object { $_.Groups[1].Value })[-1]
          if ($lastFrom -match '^(.*?)@(sha256:[a-fA-F0-9]+)(\s.*)?$') {
            $imageName = $Matches[1]
            $digest = $Matches[2]
            Write-Output "base-image-digest=${digest}" >> ${env:GITHUB_OUTPUT}
            Write-Output "base-image-name=${imageName}" >> ${env:GITHUB_OUTPUT}
          }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GitHub Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container images
        id: metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.authors=${{ format('{0}/{1}', github.server_url, github.repository_owner) }}
            org.opencontainers.image.base.digest=${{ steps.get-info-for-container.outputs.base-image-digest }}
            org.opencontainers.image.base.name=${{ steps.get-info-for-container.outputs.base-image-name }}
            org.opencontainers.image.documentation=${{ format('{0}/{1}/blob/{2}/README.md', github.server_url, github.repository, github.sha) }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}
            org.opencontainers.image.source=${{ format('{0}/{1}', github.server_url, github.repository) }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            type=edge,branch=main
            type=match,pattern=v(.*),group=1

      - name: Build and push container images
        id: push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          SOURCE_DATE_EPOCH: ${{ steps.get-info-for-container.outputs.git-commit-epoch }}
        with:
          annotations: ${{ steps.metadata.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          sbom: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          push-to-registry: true
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}

      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        env:
          # renovate: datasource=github-releases depName=cosign packageName=sigstore/cosign
          COSIGN_VERSION: v3.0.6
        with:
          cosign-release: ${{ env.COSIGN_VERSION }}

      - name: Sign container images
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
          TAGS: ${{ steps.metadata.outputs.tags }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes "{}@${DIGEST}" --annotations "ref=${GITHUB_SHA}" --annotations "repo=${GITHUB_REPOSITORY}" --annotations "workflow=${GITHUB_WORKFLOW}"
